// *****************************************************
// <!-- Section 1 : Import Dependencies -->
// *****************************************************

const express = require("express");
const bodyParser = require("body-parser");
const pgp = require('pg-promise')();
const session = require('express-session');
const bcrypt = require('bcryptjs');
const { upload, storeImage } = require('../ProjectSourceCode/storeImage');
const fs = require('fs');
const path = require('path');

// *****************************************************
// <!-- Section 2 : Initialization -->
// *****************************************************

// defining the Express app
const app = express();
// using bodyParser to parse JSON in the request body into JS objects
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));

// Database connection details
const dbConfig = {
  host: 'db',
  port: 5432,
  database: process.env.POSTGRES_DB,
  user: process.env.POSTGRES_USER,
  password: process.env.POSTGRES_PASSWORD,
};

// Connect to database using the above details
const db = pgp(dbConfig);

// Test database connection
db.connect()
  .then(obj => {
    console.log('Database connection successful');
    obj.done(); // success, release the connection;
  })
  .catch(error => {
    console.log('ERROR:', error.message || error);
  });

// Session configuration
app.use(
  session({
    secret: process.env.SESSION_SECRET || 'super_secret_key',
    saveUninitialized: false,
    resave: false,
  })
);

// Serve static files from ProjectSourceCode directory
app.use(express.static('ProjectSourceCode'));

// Serve uploaded images
app.use('/user_images', express.static('user_images'));

// *****************************************************
// <!-- Section 3 : API Routes -->
// *****************************************************

// Redirect root to home page
app.get("/", (req, res) => {
  res.redirect('/home.html');
});

app.get("/welcome", (req, res) => {
  res.json({ status: "success", message: "Welcome!" });
});

app.get('/register', (req, res) => {
  res.sendFile('register.html', { root: './ProjectSourceCode' });
});

app.post('/register', async (req, res) => {
  try {
    // Check if username already exists
    const usernameQuery = `SELECT * FROM users WHERE username = $1`;
    const existingUsername = await db.oneOrNone(usernameQuery, [req.body.username]);
    
    if (existingUsername) {
      return res.status(400).json({
        status: 'error',
        message: 'Username already taken. Please pick a different username.'
      });
    }

    // Check if email already exists (only if email provided)
    if (req.body.email) {
      const emailQuery = `SELECT * FROM users WHERE user_email = $1`;
      const existingEmail = await db.oneOrNone(emailQuery, [req.body.email]);
      
      if (existingEmail) {
        return res.status(400).json({
          status: 'error',
          message: 'Email is already registered. Please use a different email or login.'
        });
      }
    }

    // Hash password and insert new user (user_id is auto-generated by SERIAL)
    const hash = await bcrypt.hash(req.body.password, 10);
    const insertQuery = `
      INSERT INTO users (username, user_email, user_password)
      VALUES ($1, $2, $3)
      RETURNING *;
    `;
    const values = [req.body.username, req.body.email || null, hash];

    await db.query(insertQuery, values);
    res.status(200).json({
      status: 'success',
      message: 'Registration successful! Please login.'
    });
  } catch (error) {
    console.error('Registration error:', error);
    res.status(500).json({
      status: 'error',
      message: 'Registration failed. Please try again.'
    });
  }
});

app.get('/login', (req, res) => {
  res.sendFile('login.html', { root: './ProjectSourceCode' });
});

app.post('/login', async (req, res) => {
  try {
    const query = `SELECT * FROM users WHERE username = $1`;
    const user = await db.oneOrNone(query, [req.body.username]);

    if (!user) {
      return res.status(401).json({
        status: 'error',
        message: 'Username not found.'
      });
    }

    const match = await bcrypt.compare(req.body.password, user.user_password);

    if (match) {
      req.session.user = user;
      req.session.save();
      res.status(200).json({
        status: 'success',
        message: 'Login successful!',
        user: { username: user.username, user_id: user.user_id }
      });
    } else {
      res.status(401).json({
        status: 'error',
        message: 'Incorrect password.'
      });
    }
  } catch (error) {
    console.error('Login error:', error);
    res.status(500).json({
      status: 'error',
      message: 'Login failed. Please try again.'
    });
  }
});

// Upload endpoint for images
app.post('/upload', upload.single('image'), async (req, res) => {
  await storeImage(req, res, db);
});

// Get all locations with post data
app.get('/api/locations', async (req, res) => {
  try {
    const query = `
      SELECT 
        l.post_id,
        l.x_coord,
        l.y_coord,
        p.caption,
        p.date_created,
        u.username
      FROM location l
      JOIN posts p ON l.post_id = p.post_id
      JOIN users u ON p.user_id = u.user_id
      ORDER BY p.date_created DESC;
    `;
    
    const locations = await db.any(query);
    res.status(200).json({
      status: 'success',
      data: locations
    });
  } catch (error) {
    console.error('Error fetching locations:', error);
    res.status(500).json({
      status: 'error',
      message: 'Failed to fetch locations'
    });
  }
});

// Check if user is authenticated
app.get('/api/auth/check', (req, res) => {
  if (req.session.user) {
    res.status(200).json({
      status: 'success',
      authenticated: true,
      user: {
        user_id: req.session.user.user_id,
        username: req.session.user.username,
        user_email: req.session.user.user_email
      }
    });
  } else {
    res.status(200).json({
      status: 'success',
      authenticated: false
    });
  }
});

// Logout endpoint
app.get('/logout', (req, res) => {
  req.session.destroy((err) => {
    if (err) {
      return res.status(500).json({ status: 'error', message: 'Logout failed' });
    }
    res.redirect('/home.html');
  });
});

// Get current user's posts
app.get('/api/user/posts', async (req, res) => {
  try {
    if (!req.session.user) {
      return res.status(401).json({ status: 'error', message: 'Not authenticated' });
    }
    
    const query = `
      SELECT post_id, caption, date_created
      FROM posts
      WHERE user_id = $1
      ORDER BY date_created DESC;
    `;
    
    const posts = await db.any(query, [req.session.user.user_id]);
    
    // Add image path to each post, checking for actual file extension
    const postsWithImages = posts.map(post => {
      const extensions = ['.jpg', '.jpeg', '.png', '.gif', '.webp'];
      let imagePath = null;
      
      for (const ext of extensions) {
        const filePath = path.join(__dirname, '../user_images', `${post.post_id}${ext}`);
        if (fs.existsSync(filePath)) {
          imagePath = `/user_images/${post.post_id}${ext}`;
          break;
        }
      }
      
      return {
        ...post,
        image_path: imagePath || `/user_images/${post.post_id}.jpg` // fallback
      };
    });
    
    res.status(200).json({
      status: 'success',
      data: postsWithImages
    });
  } catch (error) {
    console.error('Error fetching user posts:', error);
    res.status(500).json({
      status: 'error',
      message: 'Failed to fetch posts'
    });
  }
});

// Get all posts for feed/finlog
app.get('/api/posts', async (req, res) => {
  try {
    const query = `
      SELECT 
        p.post_id,
        p.caption,
        p.date_created,
        u.username
      FROM posts p
      JOIN users u ON p.user_id = u.user_id
      ORDER BY p.date_created DESC
      LIMIT 50;
    `;
    
    const posts = await db.any(query);
    
    // Add image path to each post, checking for actual file extension
    const postsWithImages = posts.map(post => {
      const extensions = ['.jpg', '.jpeg', '.png', '.gif', '.webp'];
      let imagePath = null;
      
      for (const ext of extensions) {
        const filePath = path.join(__dirname, '../user_images', `${post.post_id}${ext}`);
        if (fs.existsSync(filePath)) {
          imagePath = `/user_images/${post.post_id}${ext}`;
          break;
        }
      }
      
      return {
        ...post,
        image_path: imagePath || `/user_images/${post.post_id}.jpg` // fallback
      };
    });
    
    res.status(200).json({
      status: 'success',
      data: postsWithImages
    });
  } catch (error) {
    console.error('Error fetching posts:', error);
    res.status(500).json({
      status: 'error',
      message: 'Failed to fetch posts'
    });
  }
});

// *****************************************************
// <!-- Section 4 : Start Server -->
// *****************************************************

module.exports = app.listen(3000, () => {
  console.log('Server is listening on port 3000');
});